#!/usr/bin/env python

import rospy
import serial

class DecawaveNode:
    def __init__(self):
        rospy.init_node('decawave_driver')
        try:
            self.ser = serial.Serial(
                port        = rospy.get_param('~port','/dev/ttyACM0s'),
                baudrate    = rospy.get_param('~baud',9600),
                timeout     = 10
            )
        except serial.SerialException:
            print("Serial Port Connection Failure")

    def run(self):
        try:
            while(not rospy.is_shutdown()):
                data = self.ser.readline().split()
                if (data[0] == 'mc' and int(data[1],16) & 0x01):
                    uwbID = str(data[9][1])
                    dist = int(data[2],16)/1000.0
                    print("Tag: " + uwbID + "    Range: " + str(dist))

        except serial.SerialException:
            self.ser.close()

        
if __name__ == "__main__":
    dw = DecawaveNode()
    dw.run()